import {
  Member,
  IPOOpportunity,
  PortfolioSummary,
  ActivityItem,
  ActionItem,
} from "@/types/nexo";

export const MOCK_MEMBERS: Member[] = [
  {
    id: "mem_1",
    name: "Ankit",
    email: "ankit@nexo.private",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "ADMIN",
    panMasked: "XXXXXXXX41",
    panFull: "ABCDE1234F",
    defaultContribution: 50000,
    joinedAt: "Jan 2025",
    phone: "+91 98200 12345",
  },
  {
    id: "mem_2",
    name: "Ashay",
    email: "ashay@nexo.private",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    role: "MEMBER",
    panMasked: "XXXXXXXX5G",
    panFull: "BCDEF2345G",
    defaultContribution: 50000,
    joinedAt: "Jan 2025",
  },
  {
    id: "mem_3",
    name: "Ranveer",
    email: "ranveer@nexo.private",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    role: "MEMBER",
    panMasked: "XXXXXXXX6H",
    panFull: "CDEFG3456H",
    defaultContribution: 30000,
    joinedAt: "Feb 2025",
  },
  {
    id: "mem_4",
    name: "Priya",
    email: "priya@nexo.private",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    role: "MEMBER",
    panMasked: "XXXXXXXX7I",
    panFull: "DEFGH4567I",
    defaultContribution: 40000,
    joinedAt: "Mar 2025",
  },
  {
    id: "mem_5",
    name: "Siddharth",
    email: "siddharth@nexo.private",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    role: "MEMBER",
    panMasked: "XXXXXXXX8J",
    panFull: "EFGHI5678J",
    defaultContribution: 50000,
    joinedAt: "Apr 2025",
  },
];

export const MOCK_IPOS: IPOOpportunity[] = [
  {
    id: "ipo_abc",
    name: "ABC Industries",
    company: "ABC Industries Limited",
    logo: "ABC",
    category: "Mainboard",
    status: "APPLICATION_OPEN",
    recommendation: "APPLY",
    thesis: "Market leader in specialty chemicals with strong export order book.",
    isFeatured: true,
    metrics: {
      issueSize: "₹1,200 Cr",
      priceBand: { min: 480, max: 500 },
      lotSize: 30,
      minInvestment: 15000,
      openDate: "12 Aug 2026",
      closeDate: "14 Aug 2026",
      allotmentDate: "19 Aug 2026",
      listingDate: "22 Aug 2026",
      gmp: 85,
      gmpPercent: 17.0,
    },
    createdBy: "Shivam Prasad",
    registrarUrl: "https://ipostatus.kfintech.com",
    participantsCount: 3,
    combinedCapital: 60000,
    tags: ["Chemicals", "High GMP"],
    applications: [
      {
        id: "app_01",
        ipoId: "ipo_abc",
        type: "INDIVIDUAL",
        applicantName: "Shivam Prasad",
        memberId: "mem_1",
        panMasked: "XXXXX1234X",
        totalContribution: 15000,
        lotCount: 1,
        verified: true,
        allotmentStatus: "ALLOTTED",
        status: "ALLOTTED",
        createdAt: "2026-08-12T10:00:00Z",
        applicationNumber: "NEXO-ABC-001",
        participants: [],
      },
      {
        id: "app_02",
        ipoId: "ipo_abc",
        type: "INDIVIDUAL",
        applicantName: "Shivam Prasad",
        memberId: "mem_1",
        panMasked: "XXXXX5678X",
        totalContribution: 15000,
        lotCount: 1,
        verified: true,
        allotmentStatus: "AWAITING",
        status: "AWAITING",
        createdAt: "2026-08-12T10:15:00Z",
        applicationNumber: "NEXO-ABC-002",
        participants: [],
      },
      {
        id: "app_03",
        ipoId: "ipo_abc",
        type: "INDIVIDUAL",
        applicantName: "Rahul Sharma",
        memberId: "mem_2",
        panMasked: "XXXXX9012X",
        totalContribution: 15000,
        lotCount: 1,
        verified: true,
        allotmentStatus: "NOT_ALLOTTED",
        status: "NOT_ALLOTTED",
        createdAt: "2026-08-12T10:30:00Z",
        applicationNumber: "NEXO-ABC-003",
        participants: [],
      },
      {
        id: "app_04",
        ipoId: "ipo_abc",
        type: "COMBINED",
        totalContribution: 15000,
        lotCount: 1,
        verified: true,
        allotmentStatus: "ALLOTTED",
        status: "ALLOTTED",
        createdAt: "2026-08-12T11:00:00Z",
        applicationNumber: "NEXO-ABC-004",
        participants: [
          {
            memberId: "mem_1",
            memberName: "Shivam Prasad",
            avatar: MOCK_MEMBERS[0].avatar,
            contribution: 5000,
            percentage: 33.3,
            panMasked: MOCK_MEMBERS[0].panMasked,
          },
          {
            memberId: "mem_2",
            memberName: "Rahul Sharma",
            avatar: MOCK_MEMBERS[1].avatar,
            contribution: 5000,
            percentage: 33.3,
            panMasked: MOCK_MEMBERS[1].panMasked,
          },
          {
            memberId: "mem_3",
            memberName: "Amit Patil",
            avatar: MOCK_MEMBERS[2].avatar,
            contribution: 5000,
            percentage: 33.4,
            panMasked: MOCK_MEMBERS[2].panMasked,
          },
        ],
      },
    ],
  },
  {
    id: "ipo_xyz",
    name: "XYZ Technologies",
    company: "XYZ Technologies India Ltd",
    logo: "XYZ",
    category: "Mainboard",
    status: "APPLICATION_OPEN",
    recommendation: "APPLY",
    thesis: "Rapidly growing SaaS platform with high recurring ARR.",
    metrics: {
      issueSize: "₹850 Cr",
      priceBand: { min: 380, max: 400 },
      lotSize: 50,
      minInvestment: 20000,
      openDate: "13 Aug 2026",
      closeDate: "15 Aug 2026",
      allotmentDate: "20 Aug 2026",
      listingDate: "25 Aug 2026",
      gmp: 60,
      gmpPercent: 15.0,
    },
    createdBy: "Shivam Prasad",
    participantsCount: 3,
    combinedCapital: 20000,
    tags: ["SaaS", "Tech"],
    applications: [
      {
        id: "app_05",
        ipoId: "ipo_xyz",
        type: "COMBINED",
        totalContribution: 20000,
        lotCount: 1,
        verified: true,
        allotmentStatus: "AWAITING",
        status: "AWAITING",
        createdAt: "2026-08-12T12:00:00Z",
        applicationNumber: "NEXO-XYZ-005",
        participants: [
          {
            memberId: "mem_1",
            memberName: "Shivam Prasad",
            avatar: MOCK_MEMBERS[0].avatar,
            contribution: 8000,
            percentage: 40.0,
            panMasked: MOCK_MEMBERS[0].panMasked,
          },
          {
            memberId: "mem_2",
            memberName: "Rahul Sharma",
            avatar: MOCK_MEMBERS[1].avatar,
            contribution: 7000,
            percentage: 35.0,
            panMasked: MOCK_MEMBERS[1].panMasked,
          },
          {
            memberId: "mem_3",
            memberName: "Amit Patil",
            avatar: MOCK_MEMBERS[2].avatar,
            contribution: 5000,
            percentage: 25.0,
            panMasked: MOCK_MEMBERS[2].panMasked,
          },
        ],
      },
    ],
  },
  {
    id: "ipo_1",
    name: "Dhoot Transmission",
    company: "Dhoot Transmission Private Limited",
    logo: "DT",
    category: "Mainboard",
    status: "APPLYING",
    recommendation: "APPLY",
    thesis:
      "Strong operating profile and attractive risk/reward based on current valuation and automotive OEM demand metrics.",
    isFeatured: false,
    closeCountdown: "1d 08h",
    metrics: {
      issueSize: "₹450 Cr",
      priceBand: { min: 245, max: 258 },
      lotSize: 58,
      minInvestment: 14964,
      openDate: "14 Aug 2026",
      closeDate: "14 Aug 2026",
      allotmentDate: "21 Aug 2026",
      listingDate: "24 Aug 2026",
      gmp: 45,
      gmpPercent: 17.4,
    },
    createdBy: "Ankit",
    participantsCount: 3,
    combinedCapital: 14964,
    tags: ["Auto Ancillary", "Profitable"],
    applications: [
      {
        id: "app_101",
        ipoId: "ipo_1",
        type: "COMBINED",
        totalContribution: 14964,
        lotCount: 1,
        verified: true,
        allotmentStatus: "AWAITING",
        status: "AWAITING",
        createdAt: "2026-08-12T14:30:00Z",
        applicationNumber: "NEXO-DT-8841",
        participants: [
          {
            memberId: "mem_2",
            memberName: "Ashay",
            avatar: MOCK_MEMBERS[1].avatar,
            contribution: 7482,
            percentage: 50.0,
            panMasked: MOCK_MEMBERS[1].panMasked,
          },
          {
            memberId: "mem_1",
            memberName: "Ankit",
            avatar: MOCK_MEMBERS[0].avatar,
            contribution: 7482,
            percentage: 50.0,
            panMasked: MOCK_MEMBERS[0].panMasked,
          },
        ],
      },
    ],
  },
  {
    id: "ipo_2",
    name: "Swiggy Limited",
    company: "Swiggy India Pvt Ltd",
    logo: "SW",
    category: "Mainboard",
    status: "APPLICATION_OPEN",
    recommendation: "APPLY",
    thesis:
      "Market leader in quick commerce (Instamart expansion) showing path to adjusted EBITDA breakeven with strong institutional demand.",
    metrics: {
      issueSize: "₹11,327 Cr",
      priceBand: { min: 371, max: 390 },
      lotSize: 38,
      minInvestment: 14820,
      openDate: "12 Aug 2026",
      closeDate: "14 Aug 2026",
      allotmentDate: "19 Aug 2026",
      listingDate: "22 Aug 2026",
      gmp: 38,
      gmpPercent: 9.7,
    },
    createdBy: "Ankit",
    participantsCount: 4,
    combinedCapital: 210000,
    tags: ["Consumer Tech", "Quick Commerce", "Unicorn"],
    applications: [
      {
        id: "app_102",
        ipoId: "ipo_2",
        type: "COMBO",
        totalContribution: 210000,
        status: "SUBMITTED",
        allotmentStatus: "AWAITING",
        createdAt: "2026-08-12T09:00:00Z",
        applicationNumber: "NEXO-SW-9021",
        participants: [
          {
            memberId: "mem_1",
            memberName: "Ankit",
            avatar: MOCK_MEMBERS[0].avatar,
            contribution: 50000,
            percentage: 23.8,
            panMasked: MOCK_MEMBERS[0].panMasked,
            status: "SUBMITTED",
          },
          {
            memberId: "mem_2",
            memberName: "Ashay",
            avatar: MOCK_MEMBERS[1].avatar,
            contribution: 50000,
            percentage: 23.8,
            panMasked: MOCK_MEMBERS[1].panMasked,
            status: "SUBMITTED",
          },
          {
            memberId: "mem_4",
            memberName: "Priya",
            avatar: MOCK_MEMBERS[3].avatar,
            contribution: 60000,
            percentage: 28.6,
            panMasked: MOCK_MEMBERS[3].panMasked,
            status: "SUBMITTED",
          },
          {
            memberId: "mem_5",
            memberName: "Siddharth",
            avatar: MOCK_MEMBERS[4].avatar,
            contribution: 50000,
            percentage: 23.8,
            panMasked: MOCK_MEMBERS[4].panMasked,
            status: "SUBMITTED",
          },
        ],
      },
    ],
  },
  {
    id: "ipo_3",
    name: "Hexaware Tech",
    company: "Hexaware Technologies Ltd",
    logo: "HT",
    category: "Mainboard",
    status: "ALLOTMENT_PENDING",
    recommendation: "APPLY",
    thesis:
      "High-margin IT services business backed by Carlyle with stable revenue visibility and multi-year digital transformation contracts.",
    metrics: {
      issueSize: "₹9,950 Cr",
      priceBand: { min: 670, max: 708 },
      lotSize: 21,
      minInvestment: 14868,
      openDate: "05 Aug 2026",
      closeDate: "08 Aug 2026",
      allotmentDate: "13 Aug 2026",
      listingDate: "16 Aug 2026",
      gmp: 110,
      gmpPercent: 15.5,
    },
    createdBy: "Ankit",
    participantsCount: 2,
    combinedCapital: 85000,
    tags: ["IT Services", "PE Backed"],
    applications: [
      {
        id: "app_103",
        ipoId: "ipo_3",
        type: "COMBO",
        totalContribution: 85000,
        status: "SUBMITTED",
        allotmentStatus: "AWAITING",
        createdAt: "2026-08-06T11:20:00Z",
        applicationNumber: "NEXO-HT-4412",
        participants: [
          {
            memberId: "mem_2",
            memberName: "Ashay",
            avatar: MOCK_MEMBERS[1].avatar,
            contribution: 45000,
            percentage: 52.9,
            panMasked: MOCK_MEMBERS[1].panMasked,
            status: "SUBMITTED",
          },
          {
            memberId: "mem_1",
            memberName: "Ankit",
            avatar: MOCK_MEMBERS[0].avatar,
            contribution: 40000,
            percentage: 47.1,
            panMasked: MOCK_MEMBERS[0].panMasked,
            status: "SUBMITTED",
          },
        ],
      },
    ],
  },
  {
    id: "ipo_4",
    name: "Bajaj Housing",
    company: "Bajaj Housing Finance Limited",
    logo: "BH",
    category: "Mainboard",
    status: "HOLDING",
    recommendation: "APPLY",
    thesis:
      "Premier non-bank housing finance player with lowest GNPA in the sector (0.28%) and strong parentage.",
    metrics: {
      issueSize: "₹6,560 Cr",
      priceBand: { min: 66, max: 70 },
      lotSize: 214,
      minInvestment: 14980,
      openDate: "09 Jul 2026",
      closeDate: "11 Jul 2026",
      allotmentDate: "16 Jul 2026",
      listingDate: "19 Jul 2026",
    },
    issuePrice: 70,
    currentPrice: 128.5,
    listingGainPercent: 15.43,
    createdBy: "Ankit",
    participantsCount: 2,
    combinedCapital: 44892,
    tags: ["NBFC", "Housing Finance", "Mega Allotment"],
    applications: [
      {
        id: "app_104",
        ipoId: "ipo_4",
        type: "COMBO",
        totalContribution: 44892,
        status: "ALLOTTED",
        allotmentStatus: "ALLOTTED",
        createdAt: "2026-07-10T10:00:00Z",
        participants: [
          {
            memberId: "mem_1",
            memberName: "Ankit",
            avatar: MOCK_MEMBERS[0].avatar,
            contribution: 22446,
            percentage: 50.0,
            panMasked: MOCK_MEMBERS[0].panMasked,
            status: "ALLOTTED",
            allotmentShares: 214,
            profitLoss: 6928,
            profitLossPercent: 15.43,
          },
          {
            memberId: "mem_2",
            memberName: "Ashay",
            avatar: MOCK_MEMBERS[1].avatar,
            contribution: 22446,
            percentage: 50.0,
            panMasked: MOCK_MEMBERS[1].panMasked,
            status: "ALLOTTED",
            allotmentShares: 214,
            profitLoss: 6928,
            profitLossPercent: 15.43,
          },
        ],
      },
    ],
  },
  {
    id: "ipo_5",
    name: "Premier Energies",
    company: "Premier Energies Limited",
    logo: "PE",
    category: "Mainboard",
    status: "SOLD",
    recommendation: "APPLY",
    thesis:
      "Integrated solar cell and module manufacturer benefiting from PLI schemes and domestic content mandates.",
    metrics: {
      issueSize: "₹2,830 Cr",
      priceBand: { min: 420, max: 450 },
      lotSize: 33,
      minInvestment: 14850,
      openDate: "27 Jun 2026",
      closeDate: "29 Jun 2026",
      allotmentDate: "03 Jul 2026",
      listingDate: "06 Jul 2026",
    },
    issuePrice: 450,
    currentPrice: 990,
    realizedProfit: 18400,
    listingGainPercent: 120.0,
    createdBy: "Ankit",
    participantsCount: 3,
    combinedCapital: 45000,
    tags: ["Solar", "Clean Energy", "Multi-bagger"],
    applications: [
      {
        id: "app_105",
        ipoId: "ipo_5",
        type: "COMBO",
        totalContribution: 45000,
        status: "ALLOTTED",
        allotmentStatus: "ALLOTTED",
        createdAt: "2026-06-28T09:15:00Z",
        participants: [
          {
            memberId: "mem_1",
            memberName: "Ankit",
            avatar: MOCK_MEMBERS[0].avatar,
            contribution: 15000,
            percentage: 33.3,
            panMasked: MOCK_MEMBERS[0].panMasked,
            status: "ALLOTTED",
            allotmentShares: 33,
            profitLoss: 6133,
          },
          {
            memberId: "mem_2",
            memberName: "Ashay",
            avatar: MOCK_MEMBERS[1].avatar,
            contribution: 15000,
            percentage: 33.3,
            panMasked: MOCK_MEMBERS[1].panMasked,
            status: "ALLOTTED",
            allotmentShares: 33,
            profitLoss: 6133,
          },
          {
            memberId: "mem_3",
            memberName: "Ranveer",
            avatar: MOCK_MEMBERS[2].avatar,
            contribution: 15000,
            percentage: 33.4,
            panMasked: MOCK_MEMBERS[2].panMasked,
            status: "ALLOTTED",
            allotmentShares: 33,
            profitLoss: 6133,
          },
        ],
      },
    ],
  },
  {
    id: "ipo_6",
    name: "Ather Energy",
    company: "Ather Energy Pvt Ltd",
    logo: "AE",
    category: "Mainboard",
    status: "WATCHLIST",
    recommendation: "WATCH",
    thesis:
      "Promising EV two-wheeler ecosystem but high cash burn rate requires careful monitoring of final listing valuation.",
    metrics: {
      issueSize: "₹3,100 Cr",
      priceBand: { min: 310, max: 330 },
      lotSize: 45,
      minInvestment: 14850,
      openDate: "28 Aug 2026",
      closeDate: "31 Aug 2026",
      allotmentDate: "03 Sep 2026",
      listingDate: "08 Sep 2026",
      gmp: 18,
      gmpPercent: 5.45,
    },
    createdBy: "Ankit",
    participantsCount: 0,
    combinedCapital: 0,
    tags: ["EV", "Automotive", "High Risk"],
    applications: [],
  },
];

export const MOCK_PORTFOLIO_SUMMARY: PortfolioSummary = {
  totalCapital: 284500,
  capitalDeployed: 184500,
  currentlyBlocked: 72000,
  availableCapital: 100000,
  totalReturn: 25650,
  totalReturnPercent: 8.91,
  realizedPnL: 18400,
  unrealizedPnL: 7250,
  activeOpportunitiesCount: 3,
  allotmentSuccessRatePercent: 66.7,
  allocation: {
    availablePercent: 35,
    blockedPercent: 25,
    investedPercent: 40,
  },
};

export const MOCK_ACTION_ITEMS: ActionItem[] = [
  {
    id: "act_item_1",
    type: "PROOF_MISSING",
    title: "Application proof missing",
    subtitle: "Ankit has not uploaded the application screenshot for Dhoot Transmission.",
    ipoId: "ipo_1",
    ipoName: "Dhoot Transmission",
    ctaLabel: "Upload proof →",
    memberName: "Ankit",
    memberAvatar: MOCK_MEMBERS[0].avatar,
  },
  {
    id: "act_item_2",
    type: "ALLOTMENT_PENDING",
    title: "Allotment pending check",
    subtitle: "Hexaware Tech allotment status expected on registrar portal today.",
    ipoId: "ipo_3",
    ipoName: "Hexaware Tech",
    ctaLabel: "Check allotment →",
  },
  {
    id: "act_item_3",
    type: "CONTRIBUTION_INCOMPLETE",
    title: "Contribution balance incomplete",
    subtitle: "Swiggy Limited ₹15,000 contribution balance remains unverified.",
    ipoId: "ipo_2",
    ipoName: "Swiggy Limited",
    ctaLabel: "Add contribution →",
    memberName: "Priya",
    memberAvatar: MOCK_MEMBERS[3].avatar,
  },
];

export const MOCK_ACTIVITIES: ActivityItem[] = [
  {
    id: "act_1",
    type: "PROOF_UPLOADED",
    title: "Ashay added Dhoot Transmission",
    subtitle: "Priced ₹245–₹258 per share • Lot size 58",
    timestamp: "12 minutes ago",
    memberName: "Ashay",
    memberAvatar: MOCK_MEMBERS[1].avatar,
    ipoId: "ipo_1",
    ipoName: "Dhoot Transmission",
  },
  {
    id: "act_2",
    type: "APPLICATION_SUBMITTED",
    title: "Ankit joined the combo application",
    subtitle: "Pooled ₹40,000 capital towards Dhoot Transmission combo pool",
    timestamp: "21 minutes ago",
    memberName: "Ankit",
    memberAvatar: MOCK_MEMBERS[0].avatar,
    ipoId: "ipo_1",
    ipoName: "Dhoot Transmission",
  },
  {
    id: "act_3",
    type: "PROOF_UPLOADED",
    title: "Application proof uploaded",
    subtitle: "Ashay verified payment transaction receipt #8841",
    timestamp: "34 minutes ago",
    memberName: "Ashay",
    memberAvatar: MOCK_MEMBERS[1].avatar,
    ipoId: "ipo_1",
    ipoName: "Dhoot Transmission",
  },
  {
    id: "act_4",
    type: "ALLOTMENT_DECLARED",
    title: "Hexaware Tech marked as allotment pending",
    subtitle: "Registrar link activated — awaiting final allotment status",
    timestamp: "2 hours ago",
    memberName: "Ankit",
    memberAvatar: MOCK_MEMBERS[0].avatar,
    ipoId: "ipo_3",
    ipoName: "Hexaware Tech",
  },
];

// Utility functions
export function formatINR(amount: number, showSign = false): string {
  const formatted = new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(Math.abs(amount));

  if (showSign && amount > 0) {
    return `+${formatted}`;
  } else if (amount < 0) {
    return `-${formatted}`;
  }
  return formatted;
}

export function maskPAN(pan: string): string {
  if (!pan || pan.length < 10) return "XXXXXXXX41";
  return `XXXXXX${pan.slice(-4)}`;
}
